id: hl7.fhir.jp.core
canonical: http://jpfhir.jp/fhir/core
name: fhir-jpcore-ig-test
title: "FHIR JP Core 実装ガイド"
description: "日本医療情報学会(JAMI) NeXEHRS課題研究会「HL7®FHIR® 日本実装検討WG」で作成した日本国内におけるベースとなるJP Core実装ガイドのドラフトVer.1 です。"
status: draft # draft | active | retired | unknown
version: 1.1.0
fhirVersion: 4.0.1
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
publisher:
  name: FHIR Japanese implementation research working group in Japan Association of Medical Informatics (JAMI)
  url: http://jpfhir.jp
  email: office@hlfhir.jp

pages:
  index.md:
    title: HL7 FHIR JP Core 実装ガイド ＜Draft Ver1.1＞
  generalGuidance.md:
    title: 総合ガイダンス
  mustSupportCardinality.md:
    title: Must SupportとCardinality(多重度)のルール
  handlingOfNonExistentData.md:
    title: 欠損値（データが存在しない場合）の扱い
  characterEncoding.md:
    title: 文字コード
  stringSearch.md:
    title: 検索
  group-administration.md:
    title: Administrationグループ
  group-medication.md:
    title: Medicationグループ
  group-diagnostic.md:
    title: Diagnosticグループ
  group-clinical.md:
    title: Clinicalグループ
  security.md:
    title: セキュリティ

menu:
  Home: index.html
  Conformance: 
    総合ガイダンス: generalGuidance.html
    Must Support Cardinality: mustSupportCardinality.html
    欠損値の扱い: handlingOfNonExistentData.html
    文字コード: characterEncoding.html
    文字列検索: stringSearch.html
  Contents:
    Administration: group-administration.html
    Medication: group-medication.html
    Diagnostic: group-diagnostic.html
    Clinical: group-clinical.html
  Artifacts: artifacts.html
  Security: security.html
