
name: JPCore FHIR Task

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  turn:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        working-directory: .
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Set up npm
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: Setup Sushi
      run: npm install
      # run: npm install -g fsh-sushi
    - name: Turn the table
      working-directory: .
      run: bundle exec rake
    # - name: Chek broken links.
    #   working-directory: .
    #   run: bundle exec rake check
