
name: JPCore FHIR Task

on:
  push:
    branches: 
     - main
     - action-test**
  pull_request:
    branches: [ main ]
    
jobs:
  turn:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v2
    # - name: Setup Ruby
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: ${{ matrix.ruby-version }}
    #     working-directory: .
    #     bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
    - name: Setup npm
      uses: actions/setup-node@v2
      with:
        check-lastest: true

    - name: Setup Sushi
      run: sudo npm install -g fsh-sushi

    - name: Install Jekyll
      run: |
        sudo apt-get install jekyll
        
    - name: Download IG Publisher
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HL7/fhir-ig-publisher
        tag: 'latest'
        path: .
        file: publisher.jar
   
    - name: Run IG Publisher
      run: | 
        mkdir input-cache
        mv publisher.jar ./input-cache/publisher.jar
        unset DISPLAY
        java -Djava.awt.headless=true -jar ./input-cache/publisher.jar -ig ig.ini
        
    # - name: Turn the table
    #   working-directory: .
    #   run: bundle exec rake
    # - name: Chek broken links.
    #   working-directory: .
    #   run: bundle exec rake check
